"""Invoice referes to Users

Revision ID: 53122c3034b4
Revises: e85d31729958
Create Date: 2025-11-28 16:22:47.925659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53122c3034b4'
down_revision: Union[str, Sequence[str], None] = 'e85d31729958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payer'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_sender'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payer'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_sender'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lineItems', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('invoices_pkey'))
    )
    op.create_index(op.f('ix_invoices_sender'), 'invoices', ['sender'], unique=False)
    op.create_index(op.f('ix_invoices_payer'), 'invoices', ['payer'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('ix_transactions_sender'), 'transactions', ['sender'], unique=False)
    op.create_index(op.f('ix_transactions_payer'), 'transactions', ['payer'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###
