"""Update users to use int

Revision ID: 71e6287310f6
Revises: 93dad39d32c4
Create Date: 2025-11-28 16:01:30.145676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e6287310f6'
down_revision: Union[str, Sequence[str], None] = '93dad39d32c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('payer', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Double(), nullable=True),
    sa.Column('lineItems', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_payer'), 'invoices', ['payer'], unique=False)
    op.create_index(op.f('ix_invoices_sender'), 'invoices', ['sender'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('payer', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('amount', sa.Double(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_payer'), 'transactions', ['payer'], unique=False)
    op.create_index(op.f('ix_transactions_sender'), 'transactions', ['sender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_sender'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payer'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_invoices_sender'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payer'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
