"""add_status_and_timestamps

Revision ID: 93d3d250937f
Revises: f05e5ba8cddb
Create Date: 2025-11-28 17:43:27.027007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d3d250937f'
down_revision: Union[str, Sequence[str], None] = 'f05e5ba8cddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('status', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    op.drop_column('invoices', 'created_at')
    op.drop_column('invoices', 'status')
    # ### end Alembic commands ###
